name: 'RaitonBL.com Versioner'
description: 'RaitonBL.com Versioner Github action'
branding:
  icon: box
  color: red
inputs:
  command:
    description: 'The command in the CLI application'
    required: true
  runtime:
    description: 'The runtime argument in the CLI application'
    required: true
  object:
    description: 'The object argument in the CLI application'
    required: true
  file:
    description: 'The file argument in the CLI application'
    required: true
  value:
    description: 'The value argument in the CLI application'
    required: false
runs:
  using: 'docker'
  image: '.github/Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.runtime }}
    - ${{ inputs.object }}
    - ${{ inputs.file }}
    - ${{ inputs.value }}